before:
  hooks:
    - go mod vendor
    - ./scripts/prepare.sh
builds:
  - id: netauth
    main: ./cmd/netauth/main.go
    binary: netauth
    goos:
      - darwin
      - freebsd
      - linux
      - windows
  - id: netauthd
    main: ./cmd/netauthd/main.go
    binary: netauthd
    goos:
      - darwin
      - freebsd
      - linux
      - windows
archives:
- files:
    - LICENSE
    - NOTICE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: NetAuth
    name: NetAuth
