project_name: netauth
version: 2
before:
  hooks:
    - go mod vendor
    - ./scripts/prepare.sh
builds:
  - id: netauth
    main: ./cmd/netauth/main.go
    binary: netauth
    goos:
      - darwin
      - freebsd
      - linux
      - windows
  - id: netauthd
    main: ./cmd/netauthd/main.go
    binary: netauthd
    goos:
      - darwin
      - freebsd
      - linux

archives:
  - files:
    - LICENSE
    - NOTICE
    - README.md
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: NetAuth
    name: NetAuth
