// Code generated by "stringer -type=PluginAction"; DO NOT EDIT.

package common

import "strconv"

const _PluginAction_name = "EntityCreateEntityUpdateEntityLockEntityUnlockEntityDestroyGroupCreateGroupUpdateGroupDestroyPreSecretChangePostSecretChangePreAuthCheckPostAuthCheckPreTokenAuthPostTokenAuth"

var _PluginAction_index = [...]uint8{0, 12, 24, 34, 46, 59, 70, 81, 93, 108, 124, 136, 149, 161, 174}

func (i PluginAction) String() string {
	if i < 0 || i >= PluginAction(len(_PluginAction_index)-1) {
		return "PluginAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PluginAction_name[_PluginAction_index[i]:_PluginAction_index[i+1]]
}
